title: "The Friday Pint Club"
description: "Pints, Fridays, memes."
baseurl: "" # leave blank for user/organization sites
url: "https://GuyCarter-Richardson.github.io"     # Leave empty unless using custom domain

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site navigation (if used in layout)
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Pubs"
    url: "/pubs/"
  - title: "Pints"
    url: "/pints/"
  - title: "(In)Famous Quotes"
    url: "/quotes/"
