title: "Friday Pint Club"
description: "A casual club for good pints, good company, and better Fridays."
baseurl: "" # leave blank for user/organization sites
url: "https://GuyCarter-Richardson.github.io"     # Leave empty unless using custom domain

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site navigation (if used in layout)
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
